#!/usr/bin/env perl

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;
use FindBin '$Bin';

use Benchmark::Command;

Benchmark::Command::run(
    undef,
    {
        'none'                    => [$^X, "-I$Bin/../lib", "-e1"],
        'Perinci::Examples::Tiny' => [$^X, "-I$Bin/../lib", "-e", "use Perinci::Examples::Tiny;"],
        'Perinci::Examples::CLI'  => [$^X, "-I$Bin/../lib", "-e", "use Perinci::Examples::CLI;"],
        'Perinci::Examples'       => [$^X, "-I$Bin/../lib", "-e", "use Perinci::Examples;"],
    },
);
